### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gituser12981u2** [gituser12981u2/stress_visualization#1]
This serves as a high level overview roadmap of what is to be implemented.

## Features

- [x] Graph Toggle
- [ ] Add a direct stress input method
- [ ] Add a Mohr Cycle visualization
- [ ] Add a load-based calculation method based on common loading scenarios (axial, bending, torsion)
- [ ] Material-based examples (steal_beam_bending, aluminum tube_torsion)
etc...
